In [45]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [46]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [47]:
df = pd.read_csv("C:\\Users\\wasim\\Downloads\\archive (1)\\anime.csv")

In [48]:
df.head()

,anime_id,name,genre,type,episodes,rating,members
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262
3,9253,Steins;Gate,"Sci-Fi, Thriller",TV,24,9.17,673572
4,9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.16,151266

In [49]:
print(df.head())
print(df.columns.tolist())

   anime_id                              name  \
0     32281                    Kimi no Na wa.
1      5114  Fullmetal Alchemist: Brotherhood
2     28977                          Gintama°
3      9253                       Steins;Gate
4      9969                     Gintama&#039;

                                               genre   type episodes  rating  \
0               Drama, Romance, School, Supernatural  Movie        1    9.37
1  Action, Adventure, Drama, Fantasy, Magic, Mili...     TV       64    9.26
2  Action, Comedy, Historical, Parody, Samurai, S...     TV       51    9.25
3                                   Sci-Fi, Thriller     TV       24    9.17
4  Action, Comedy, Historical, Parody, Samurai, S...     TV       51    9.16

   members
0   200630
1   793665
2   114262
3   673572
4   151266
['anime_id', 'name', 'genre', 'type', 'episodes', 'rating', 'members']

In [50]:
df.shape

(12294, 7)

In [51]:
df.columns

Index(['anime_id', 'name', 'genre', 'type', 'episodes', 'rating', 'members'], dtype='str')

In [52]:
df.info

<bound method DataFrame.info of        anime_id                                               name  \
0         32281                                     Kimi no Na wa.
1          5114                   Fullmetal Alchemist: Brotherhood
2         28977                                           Gintama°
3          9253                                        Steins;Gate
4          9969                                      Gintama&#039;
...         ...                                                ...
12289      9316       Toushindai My Lover: Minami tai Mecha-Minami
12290      5543                                        Under World
12291      5621                     Violence Gekiga David no Hoshi
12292      6133  Violence Gekiga Shin David no Hoshi: Inma Dens...
12293     26081                   Yasuji no Pornorama: Yacchimae!!

                                                   genre   type episodes  \
0                   Drama, Romance, School, Supernatural  Movie        1
1      Action, Adventure, Drama, Fantasy, Magic, Mili...     TV       64
2      Action, Comedy, Historical, Parody, Samurai, S...     TV       51
3                                       Sci-Fi, Thriller     TV       24
4      Action, Comedy, Historical, Parody, Samurai, S...     TV       51
...                                                  ...    ...      ...
12289                                             Hentai    OVA        1
12290                                             Hentai    OVA        1
12291                                             Hentai    OVA        4
12292                                             Hentai    OVA        1
12293                                             Hentai  Movie        1

       rating  members
0        9.37   200630
1        9.26   793665
2        9.25   114262
3        9.17   673572
4        9.16   151266
...       ...      ...
12289    4.15      211
12290    4.28      183
12291    4.88      219
12292    4.98      175
12293    5.46      142

[12294 rows x 7 columns]>

In [53]:
df.isnull().sum()

anime_id      0
name          0
genre        62
type         25
episodes      0
rating      230
members       0
dtype: int64

In [54]:
df.describe

<bound method NDFrame.describe of        anime_id                                               name  \
0         32281                                     Kimi no Na wa.
1          5114                   Fullmetal Alchemist: Brotherhood
2         28977                                           Gintama°
3          9253                                        Steins;Gate
4          9969                                      Gintama&#039;
...         ...                                                ...
12289      9316       Toushindai My Lover: Minami tai Mecha-Minami
12290      5543                                        Under World
12291      5621                     Violence Gekiga David no Hoshi
12292      6133  Violence Gekiga Shin David no Hoshi: Inma Dens...
12293     26081                   Yasuji no Pornorama: Yacchimae!!

                                                   genre   type episodes  \
0                   Drama, Romance, School, Supernatural  Movie        1
1      Action, Adventure, Drama, Fantasy, Magic, Mili...     TV       64
2      Action, Comedy, Historical, Parody, Samurai, S...     TV       51
3                                       Sci-Fi, Thriller     TV       24
4      Action, Comedy, Historical, Parody, Samurai, S...     TV       51
...                                                  ...    ...      ...
12289                                             Hentai    OVA        1
12290                                             Hentai    OVA        1
12291                                             Hentai    OVA        4
12292                                             Hentai    OVA        1
12293                                             Hentai  Movie        1

       rating  members
0        9.37   200630
1        9.26   793665
2        9.25   114262
3        9.17   673572
4        9.16   151266
...       ...      ...
12289    4.15      211
12290    4.28      183
12291    4.88      219
12292    4.98      175
12293    5.46      142

[12294 rows x 7 columns]>

In [55]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])
print("\nColumns Names:")
print(df.columns)
print("\nDataset Information:")
df.info()

Rows: 12294
Columns: 7

Columns Names:
Index(['anime_id', 'name', 'genre', 'type', 'episodes', 'rating', 'members'], dtype='str')

Dataset Information:
<class 'pandas.DataFrame'>
RangeIndex: 12294 entries, 0 to 12293
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   anime_id  12294 non-null  int64
 1   name      12294 non-null  str
 2   genre     12232 non-null  str
 3   type      12269 non-null  str
 4   episodes  12294 non-null  str
 5   rating    12064 non-null  float64
 6   members   12294 non-null  int64
dtypes: float64(1), int64(2), str(4)
memory usage: 1.3 MB

In [56]:
df = df.dropna(subset=["name"]).copy()

In [30]:
df = df.reset_index(drop=True)

indices = pd.Series(
    df.index,
    index=df["name"]
).drop_duplicates()

In [31]:
df.isnull().sum()

anime_id      0
name          0
genre        62
type         25
episodes      0
rating      230
members       0
dtype: int64

In [32]:
df["combined_features"] = (
    df["genre"].astype(str) +" "+
    df["type"].astype(str)
)
df[["name", "combined_features"]].head()

,name,combined_features
0,Kimi no Na wa.,"Drama, Romance, School, Supernatural Movie"
1,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili..."
2,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S..."
3,Steins;Gate,"Sci-Fi, Thriller TV"
4,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S..."

In [57]:
df["combined_features"] = (
    df["genre"].astype(str) + " " +
    df["type"].astype(str)
).str.strip()

df[["name", "genre", "type", "rating"]].head()

,name,genre,type,rating
0,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,9.37
1,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,9.26
2,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,9.25
3,Steins;Gate,"Sci-Fi, Thriller",TV,9.17
4,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV,9.16

In [58]:
df["combined_features"] = df["combined_features"].replace("", "unknown")

In [66]:
df["genre"] = df["genre"].fillna("")
df["type"] = df["type"].fillna("")

# Rebuild combined_features
df["combined_features"] = (
    df["genre"].astype(str) + " " +
    df["type"].astype(str)
).str.strip()

# Replace empty values
df["combined_features"] = df["combined_features"].replace(
    r"^\s*$", "unknown", regex=True
)

# Verify
print("Missing values:", df["combined_features"].isna().sum())

Missing values: 0

In [67]:

tfidf = TfidfVectorizer(stop_words="english")

tfidf_matrix = tfidf.fit_transform(
    df["combined_features"]
)

cosin_sim = cosine_similarity(tfidf_matrix)

print("Similarity matrix created successfully!")
print("Similarity matrix shape:", cosin_sim.shape)

Similarity matrix created successfully!
Similarity matrix shape: (12294, 12294)

In [68]:
cosine_sim = cosine_similarity(tfidf_matrix)
print("Cosine Similarity Shape:")
print(cosine_sim.shape)

Cosine Similarity Shape:
(12294, 12294)

In [69]:
indices = pd.Series(df.name,index=df["name"]).drop_duplicates()

In [70]:
def recommend_anime(anime_name, num_recommendation=5):

    if anime_name not in indices.index:
        return "Anime not found in dataset."
    anime_index = int(indices.loc[anime_name])

    similarity_scores = list(
        enumerate(cosin_sim[anime_index])
    )

    similarity_scores = sorted(
        similarity_scores,
        key=lambda x: x[1],
        reverse=True
    )

    similarity_scores = [
        item for item in similarity_scores
        if item[0] != anime_index
    ]

    similarity_scores = similarity_scores[
        :num_recommendation
    ]

    anime_indices = [i[0] for i in similarity_scores]

    result = df.iloc[anime_indices][
        ["name", "genre", "type", "rating"]
    ].copy()

    result["similarity_score"] = [
        round(i[1], 3)
        for i in similarity_scores
    ]

    return result.reset_index(drop=True)

In [71]:
recommend_anime("One Piece")

'Anime not found in dataset.'

In [72]:
recommend_anime("Gintama°")

'Anime not found in dataset.'

In [73]:
recommend_anime("Fullmetal Alchemist: Brotherhood", 5)

'Anime not found in dataset.'

In [ ]:
recommend_anime("iron man")

In [75]:
similarity_df = pd.DataFrame(
    cosine_sim,
    index=df["name"],
)
similarity_df.head()

,0,1,2,3,4,5,6,7,8,9,...,12284,12285,12286,12287,12288,12289,12290,12291,12292,12293
name,,,,,,,,,,,,,,,,,,,,,
Kimi no Na wa.,1.000000,0.132086,0.000000,0.00000,0.000000,0.374399,0.000000,0.138681,0.100247,0.000000,...,0.0,0.243935,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.237599
Fullmetal Alchemist: Brotherhood,0.132086,1.000000,0.223293,0.07367,0.223293,0.337494,0.386069,0.378346,0.166887,0.223293,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000
Gintama°,0.000000,0.223293,1.000000,0.26952,1.000000,0.235218,0.243068,0.186767,0.942538,1.000000,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000
Steins;Gate,0.000000,0.073670,0.269520,1.00000,0.269520,0.087390,0.080195,0.252393,0.203987,0.269520,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000
Gintama&#039;,0.000000,0.223293,1.000000,0.26952,1.000000,0.235218,0.243068,0.186767,0.942538,1.000000,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000

In [ ]:
print(similarity_df.shape)
print(similarity_df.columns[:10].tolist())

In [ ]:
similarity_df = pd.DataFrame(
    cosin_sim,
    index=df["name"],
    columns=df["name"]
)

In [ ]:
similarity_df["Gintama°"].drop(
    "Gintama°",
    errors="ignore"
).sort_values(ascending=False).head(10)

In [ ]:
recommendation = recommend_movies("Gintama°", 5)
recommendation